#Local MySQL url: spring.datasource.url=jdbc:mysql://localhost:3306/usermanager?allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://8TuY4qC14yN68cp.root:${DB_PASSWORD}@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/usermanager?sslMode=VERIFY_IDENTITY
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create

spring.application.name=User Manager Galluccio
server.port=8080
server.servlet.context-path=/usermanager